#邮件配置
spring:
  mail:
    host: 10.48.6.12
    port: 587
    username: luxshare\BU3.SERVER
    password: Luxshare@2021#
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
    to: Jiapeng.Xu@luxshare-ict.com
    cc:
    cc1: